using GUPS.Obfuscator.Attribute;

namespace Bulbul.Achievements;

[DoNotRename]
public enum AchievementCategory
{
	COMPLETE_TUTORIAL_COUNT,
	COMPLETE_TODO_COUNT,
	COMPLETE_POMODORO_COUNT,
	END_EDIT_NOTE_COUNT,
	END_EDIT_DIARY_COUNT,
	IMPORT_MUSIC_COUNT,
	CHANGE_ENVIROMENT_COUNT,
	FINISH_GAME_FROM_EXIT_CALL_BUTTON_COUNT,
	TALK_WORKING_COUNT,
	TALK_BREAKING_COUNT,
	TALK_AFTER_WORK_COUNT,
	SMALL_TALK_CAT_HEADPHONE,
	SMALL_TALK_GALAXY_EXPRESS,
	SMALL_TALK_HEATSTROKE,
	SMALL_TALK_CHICADA,
	POMODORO_WORK_HOURS_COUNT,
	READ_ALL_MAIN_STORY,
	READ_GLASSES_STORY,
	CLICK_KOU_COUNT,
	DRINK_HOT,
	WAKE_UP_HEROINE,
	PUBLISH_SUMMERTIME_OVERDRIVE
}
